# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
print(np.__version__)
np.show_config

2.0.1


<function numpy.__config__.show(mode='stdout')>

#### 3. Create a null vector of size 10 (★☆☆)

In [9]:
array1 = np.zeros((1,10))
array1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 4. How to find the memory size of any array (★☆☆)

In [11]:
memory_size_1 = array1.nbytes
memory_size_2 = array1.size * array1.itemsize

print(f'size1:{memory_size_1}')
print(f'size2:{memory_size_2}')

size1:80
size2:80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [12]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [26]:
array = np.zeros(10)
# np.put(array, 4, 1)
array[4] = 1
array

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [17]:
array = np.arange(10,50)
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [27]:
array = np.arange(1,11)
# array = array[::-1]
array = np.flipud(array)
array

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [30]:
# array = np.matrix('0 1 2;3 4 5;6 7 8')
array = np.arange(9).reshape(3,3)
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [33]:
np.nonzero([1,2,0,0,2,0])

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [35]:
array = np.eye(3)
print(array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [58]:
array = np.random.rand(3,3,3)
print(array)

[[[0.80337582 0.10822019 0.09043826]
  [0.05596006 0.77156006 0.42641812]
  [0.7841017  0.675329   0.01233308]]

 [[0.40099687 0.42481896 0.41974439]
  [0.36355563 0.63628728 0.79447393]
  [0.6793647  0.58977113 0.64381993]]

 [[0.84135481 0.78852728 0.48477103]
  [0.91835254 0.68974429 0.63981184]
  [0.87667388 0.94895533 0.64080599]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [59]:
array = np.random.rand(10,10)
print(array)
print(f'max:{array.max()}')
print(f'min:{array.min()}')

[[0.61189267 0.8498677  0.96001297 0.00366212 0.55753931 0.71130147
  0.19124837 0.49734607 0.10922728 0.57335943]
 [0.47386264 0.78033196 0.7174749  0.40447487 0.69486602 0.12110316
  0.95635012 0.68352736 0.34944972 0.08226306]
 [0.4717626  0.77257587 0.45740594 0.73842352 0.63223446 0.72656865
  0.14683286 0.32085395 0.7850358  0.19593815]
 [0.22797898 0.83027775 0.3493832  0.0182847  0.29663144 0.73985663
  0.2412263  0.80234114 0.87780941 0.88506624]
 [0.53254422 0.03105401 0.47245755 0.81950175 0.19940052 0.1067676
  0.59216608 0.17902168 0.11021345 0.79794913]
 [0.61931492 0.44605294 0.27672327 0.31007322 0.30973315 0.17870517
  0.38948667 0.65084258 0.26986719 0.04214542]
 [0.16253544 0.07912319 0.75583517 0.80852791 0.43200408 0.42011426
  0.517264   0.11517234 0.25796853 0.9712919 ]
 [0.78485074 0.94253515 0.19787469 0.2209925  0.37802695 0.55329619
  0.42910521 0.91242985 0.37037757 0.95522388]
 [0.77735625 0.02219882 0.76995385 0.80083192 0.48457028 0.14912742
  0.80499272 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [60]:
vector = np.random.rand(30)
m = np.mean(vector)
print(vector)
print(f'mean:{m}')

[0.11238224 0.03436453 0.32981405 0.52482904 0.44692229 0.41708748
 0.05023161 0.08904346 0.74977079 0.69266956 0.73908118 0.01884851
 0.49093502 0.70705459 0.83148377 0.44793675 0.8436362  0.99283671
 0.67841194 0.19298158 0.96550587 0.77970249 0.33852638 0.76710467
 0.61625295 0.7580633  0.49957953 0.98960055 0.94849914 0.60183802]
mean:0.5551664732689877


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [57]:
array = np.ones([4,4])
array[1:-1,1:-1] = 0
print(array)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [80]:
array = np.ones((2,3))
# m = np.size(array,0)
# n = np.size(array,1)
# z = np.zeros((m+2,n+2))
# z[1:-1,1:-1] = array
z = np.pad(array, pad_width= 1,mode = 'constant', constant_values = 0)
print(z)


[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [90]:
np.nan
False
False
np.nan
True
False

True

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [105]:
arr = np.diag(np.arange(1,5),-1)
print(arr)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [106]:
a = np.eye(8)
a[0::2,0::2] = 1
a[1::2,1::2] = 1
print(a)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [119]:
a = np.arange(6*7*8).reshape(6,7,8)
index = np.where(a==99)
print(index)
print(np.unravel_index(100, (6, 7, 8)))


(array([1]), array([5]), array([3]))
(np.int64(1), np.int64(5), np.int64(4))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [122]:
a = np.array([[1,0],[0,1]])
b = np.tile(a,(4,4))
print(b)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [133]:
a = np.random.rand(5,5)
b = (a - a.mean())/a.std()
print(b)

[[ 0.06412796  0.55382849  1.33437768  1.04366401 -1.61547378]
 [-1.77487645  0.05609939  0.94401393  1.31339022 -0.01093285]
 [ 1.09303061 -1.18535434 -0.07358323  1.26157898 -0.79213454]
 [ 0.4098514  -0.15965515 -0.2055216   0.99725324 -0.50495193]
 [-0.37737889  0.85681609 -1.69955219  0.28382927 -1.81244631]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [135]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(color)


[('r', 'u1', (1,)), ('g', 'u1', (1,)), ('b', 'u1', (1,)), ('a', 'u1', (1,))]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [146]:
a = np.random.rand(5,3)
b = np.random.rand(3,2)
a@b

array([[1.2884587 , 1.01212669],
       [1.66588305, 1.17127302],
       [1.29504126, 0.86242481],
       [0.73618932, 0.51733806],
       [0.75990003, 0.59774209]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [154]:
Z = np.arange(11)
(3 >= Z) | (Z >= 8)


array([ True,  True,  True,  True, False, False, False, False,  True,
        True,  True])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [156]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [163]:
a = np.arange(3)
a**a
2 << a >> 2


array([0, 1, 2])

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [166]:
np.array(0)/np.array(0)
np.array(0)//np.array(0)
np.array([np.nan]).astype(int).astype(float)

C:\Users\susiyi\AppData\Local\Temp\ipykernel_31304\3064765101.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0)/np.array(0)
C:\Users\susiyi\AppData\Local\Temp\ipykernel_31304\3064765101.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0)//np.array(0)
C:\Users\susiyi\AppData\Local\Temp\ipykernel_31304\3064765101.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [167]:
Z = np.random.uniform(-10, +10, 10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

'More readable but less efficient'
print(np.where(Z > 0, np.ceil(Z), np.floor(Z)))


[ 10.   9.  -7.  -5.   5.  -8.  -2.   9.   6. -10.]
[ 10.   9.  -7.  -5.   5.  -8.  -2.   9.   6. -10.]


#### 30. How to find common values between two arrays? (★☆☆)

In [173]:
a = np.arange(5)
b = np.arange(3,7)
c = np.intersect1d(a,b)
print(c)

[3 4]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [174]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\susiyi\AppData\Local\Temp\ipykernel_31304\244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


np.False_

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [177]:
today = np.datetime64('today')
yesterday = today - np.timedelta64(1)

print(today)
print(yesterday)

2025-04-02
2025-04-01


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [179]:
a = np.arange('2016-07','2016-08',dtype = 'datetime64[D]')
print(a)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [180]:
a = np.ones(3)
b = a
np.add(a,b,out=b)
np.divide(a,2,out=a)
np.negative(a,out=a)
np.multiply(a,b,out=a)
print(a)

[1. 1. 1.]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [192]:
Z = np.random.uniform(0, 10, 10)

print(Z)
print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[6.10900429 8.36001438 1.5629136  0.2821868  6.75188818 1.60653901
 7.18857935 2.53074696 0.38610818 6.1500714 ]
[6. 8. 1. 0. 6. 1. 7. 2. 0. 6.]
[6. 8. 1. 0. 6. 1. 7. 2. 0. 6.]
[6. 8. 1. 0. 6. 1. 7. 2. 0. 6.]
[6 8 1 0 6 1 7 2 0 6]
[6. 8. 1. 0. 6. 1. 7. 2. 0. 6.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [194]:
a = np.tile(np.arange(5),(5,1))
a

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [204]:
def generate():
    for i in range(10):
        yield i
a = np.fromiter(generate(),dtype = 'int32', count=-1)
a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [207]:
a = np.linspace(0,1,12)[1:-1]
a

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [209]:
a = np.sort(np.random.rand(10))
a

array([0.01178596, 0.04612033, 0.06903027, 0.2881546 , 0.39547712,
       0.42689613, 0.55463702, 0.75163974, 0.86987092, 0.99750476])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [210]:
a = np.arange(10)
print(np.add.reduce(a))

45


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [212]:
a = np.random.rand(10)
b = np.random.rand(10)
equal = np.array_equal(a,b)
print(equal)

False


#### 43. Make an array immutable (read-only) (★★☆)

In [215]:
a = np.arange(10)
a.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [231]:
a = np.random.rand(10,2)
r = np.sqrt(a[:,0]**2 + a[:,1]**2)
th = np.arctan2(a[:,1],a[:,0])
print(r)
print(th)

[0.63930448 0.91855796 1.25024479 0.55144109 1.23519593 1.32730192
 0.96695822 0.79913498 0.9360011  1.01067093]
[0.37249784 0.5061642  0.73048803 0.81833003 0.91744498 0.73288796
 0.57356741 0.75091926 0.39619416 1.22147209]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [249]:
a = np.random.rand(10)
a[np.argmax(a)] = 0
print(a)

[0.54310728 0.81981531 0.23072174 0.98317342 0.28423641 0.18209081
 0.27495024 0.11495788 0.         0.72587683]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [253]:
Z = np.zeros((5, 5), [('x', float), ('y', float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [268]:
x = np.random.rand(5)
y = np.random.rand(5)

yy,xx = np.meshgrid(y,x) # 注意meshgrid的计算顺序
c = 1/(xx-yy)
print(np.linalg.det(c))

C = 1.0 / np.subtract.outer(x, y)
print(np.linalg.det(C))

-0.8905058320488315
-0.8905058320488315


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [269]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [278]:
a = np.random.rand(2,3)
for i in a:
    print(i)

np.set_printoptions(threshold = float("inf"))
Z = np.zeros((4,4))
print(Z)

[0.54184001 0.03014526 0.14204059]
[0.50970443 0.70733157 0.88576911]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [281]:
a = np.random.rand(5)
scalar = 0.5
b = np.abs(a - scalar)
print(np.argmin(b))

0


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [292]:
position = np.dtype([('x',float),('y',float)])
color = np.dtype([('r',np.ubyte),
                  ('g',np.ubyte),
                  ('b',np.ubyte)])
combined = np.dtype([('position',position),
                     ('color',color)])
a = np.zeros(2,dtype=combined)
print(a)

[((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [303]:
a = np.random.rand(10,2)
x,y = np.atleast_2d(a[:,0],a[:,1])
# 如果直接将x和y分离，得到的是一维数组，此时无法实现x-xT
distance = np.sqrt((x-x.T)**2 + (y-y.T)**2)
print(distance)

[[ 0.         -0.45021185 -0.37908904 -0.33869505  0.16733045  0.24186576
  -0.55340422 -0.02381922  0.06807314 -0.19875199]
 [ 0.45021185  0.          0.07112282  0.1115168   0.61754231  0.69207762
  -0.10319237  0.42639263  0.518285    0.25145986]
 [ 0.37908904 -0.07112282  0.          0.04039398  0.54641949  0.6209548
  -0.17431518  0.35526981  0.44716218  0.18033704]
 [ 0.33869505 -0.1115168  -0.04039398  0.          0.50602551  0.58056081
  -0.21470917  0.31487583  0.40676819  0.13994306]
 [-0.16733045 -0.61754231 -0.54641949 -0.50602551  0.          0.07453531
  -0.72073468 -0.19114968 -0.09925731 -0.36608245]
 [-0.24186576 -0.69207762 -0.6209548  -0.58056081 -0.07453531  0.
  -0.79526998 -0.26568498 -0.17379262 -0.44061776]
 [ 0.55340422  0.10319237  0.17431518  0.21470917  0.72073468  0.79526998
   0.          0.529585    0.62147736  0.35465223]
 [ 0.02381922 -0.42639263 -0.35526981 -0.31487583  0.19114968  0.26568498
  -0.529585    0.          0.09189236 -0.17493277]
 [-0.0680

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [310]:
a = np.arange(5,dtype=float32)
a = a.astype(np.int32,copy = False)
print(a)

[0 1 2 3 4]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [317]:
file = '100_numpy_54.txt'
f = np.genfromtxt(file, dtype = int, delimiter=',') # dtype=str
print(f)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [336]:
a = np.array([[1,2],[3,4]])

for index,value in np.ndenumerate(a):
    print(index,value)

for index in np.ndindex(a.shape):
    print(index,a[index])

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4
(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [338]:
# 不理解什么叫做“高斯阵列gaussian-like array”
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print (G.shape)

(10, 10)


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [355]:
a = np.random.rand(2,5)
p = 3
rep = np.zeros(3)
flat_indices = np.random.choice(a.size,p,replace = False)
np.put(a,flat_indices,rep)
print(a)
# 重点在于choice选择索引，因为put需要索引而非值

[[0.91649328 0.40161639 0.31942446 0.7181591  0.14253415]
 [0.97386113 0.52148253 0.32486095 0.50012756 0.31336043]]
10
[[0.         0.40161639 0.31942446 0.7181591  0.        ]
 [0.97386113 0.52148253 0.32486095 0.         0.31336043]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [358]:
a = np.eye(3)
mean_value = np.mean(a, axis = 1, keepdims = True)
print(a-mean_value)

[[0.33333333]
 [0.33333333]
 [0.33333333]]
[[ 0.66666667 -0.33333333 -0.33333333]
 [-0.33333333  0.66666667 -0.33333333]
 [-0.33333333 -0.33333333  0.66666667]]


#### 59. How to sort an array by the nth column? (★★☆)

In [368]:
a = np.random.rand(3,4)
n = 1
print(a)
print(a[a[:,n].argsort()])

[[0.73888795 0.16659864 0.23341223 0.78156973]
 [0.19844888 0.23915302 0.30366431 0.76209715]
 [0.83721661 0.65631802 0.04593649 0.81051879]]
[[0.73888795 0.16659864 0.23341223 0.78156973]
 [0.19844888 0.23915302 0.30366431 0.76209715]
 [0.83721661 0.65631802 0.04593649 0.81051879]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [371]:
a = np.random.rand(2,5)
print ((~a.any(axis = 0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [376]:
a = np.random.rand(2,5)
b = 0.5
n = a.flat[np.abs(a-b).argmin()]
print(n)

0.5147331531872685


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [378]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
print(it)
for x,y,z in it: 
    z[...] = x + y
print (it.operands[2])
# 没有看懂，难难的

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [379]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [380]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[3. 3. 4. 3. 3. 4. 3. 4. 2. 1.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [383]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print (F)
# I提供索引，X的每一个值按照I中对应的索引添加到F的对应位置

[7 2 7 5 4 3 7 8 4 3]
[0. 0. 1. 2. 2. 1. 0. 3. 1.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [12]:
import numpy as np
w = h = 5
image = np.random.randint(0,256,(w,h,3)).astype(np.ubyte)
print(len(np.unique(image)))


65


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [16]:
a = np.random.rand(2,2,2,2)
print(np.sum(a,axis = (-2,-1)))

[[3.43132344 2.17500878]
 [1.92000387 2.8394378 ]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [17]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print (D_means)
# 这次是真的完全没懂，为什么要计算加权平均值

[0.38970905 0.51123118 0.42042355 0.5612144  0.58103283 0.7247824
 0.48496    0.57927453 0.78860478 0.38576278]


#### 69. How to get the diagonal of a dot product? (★★★)

In [19]:
a = np.random.rand(5,5)
b = np.random.rand(5,5)
diag = np.diag(np.dot(a,b))
# diag = np.sum(a*b.T,axis = 1)
print(diag)

[1.36443044 1.30249057 1.59548981 1.52077723 1.6064485 ]
[1.36443044 1.30249057 1.59548981 1.52077723 1.6064485 ]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [21]:
a = np.array([1,2,3,4,5])
b = np.zeros(np.size(a) + 3*(np.size(a)-1))
b[::4] = a
print(b)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [33]:
a = np.random.rand(5,5,3)
b = np.random.rand(5,5)
c = a*b[:,:,None]
print(c)

(5, 5, 3)


#### 72. How to swap two rows of an array? (★★★)

In [36]:
a = np.arange(8).reshape(4,2)
x,y = 1,2
a[[x,y],:] = a[[y,x],:]
print(a)

[[0 1]
 [4 5]
 [2 3]
 [6 7]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [ ]:
# too difficult

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [37]:
c = np.array([0,1,1,2,4,6,8,8])
c_bin = np.bincount(c)
a = np.repeat(np.arange(len(c_bin)),c_bin)
print(a)

[0 1 1 2 4 6 8 8]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [39]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)

print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)